baseurl = "/"
config = "config.toml"
contentDir = "public/content"
dataDir = "public/data"
defaultContentLanguage = "en"
disable404 = false
disableHugoGeneratorInject = false
disableKinds = ["RSS"]
disqusShortname = "janchristianbernabe-1"
enableEmoji= true
enableRobotsTXT = true
googleAnalytics = "UA-31354104-1"
languageCode = "en-us"
layoutDir = "public/layouts"
metaDataFormat = "toml"
publishDir = "public"
resourceDir = "public/resources"
staticDir = "public/static"
title = "Jan Christian Bernabe, Ph.D. | Polymath"
uglyURLs = true

[imaging]
resampleFilter = "Gaussian"
quality = 65
anchor = "smart"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[params]
  title = "Jan Christian Bernabe"
  description = '<!--[-->Thought Leader | Maker | Growth Hacker | Polymath<!--]--><p></p>
                <!--[--><i class="far fa-id-card fa-2x"></i><!--]--><br />
                <!--[--><p>Nerd</p><!--]-->'
  logo = "fas fa-bolt fa-2x"
  copyright = "Jan Christian Bernabe, Ph.D."

[params.disqus]
  site = ""

[params.google.analytics]
  trackerID = "UA-31354104-1"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/janchristianbernabe"
  weight = "10"

[[params.social]]
  medium = "amazon"
  icon = "amazon"
  link = "https://www.amazon.com/Jan-Christian-Bernabe/e/B06W541XK7/ref=dp_byline_cont_ebooks_2"
  weight = "20"

[[params.social]]
  medium = "quora"
  icon = "quora"
  link = "https://www.quora.com/profile/Jan-Christian-Bernabe"
  weight = "30"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://www.twitter.com/spramp"
  weight = "40"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://www.github.com/spramp"
  weight = "50"

[[params.social]]
    medium = "spotify"
    icon = "spotify"
    link = "https://open.spotify.com/user/spramp"
    weight = "60"

[languages]
[languages.en]
languageName = "English"
weight = 1

#[Params.seo.webmaster_verifications]#
  # google = "" # Optional, Google verification code
  # bing = "" # Optional, Bing verification code
  # alexa = "" # Optional, Alexa verification code
  # yandex = "" # Optional, Yandex verification code
