archetypeDir = "content/archetypes"
baseurl = "/"
config = "config.toml"
contentDir = "public/content"
dataDir = "public/data"
defaultContentLanguage = "en"
disable404 = false
disableHugoGeneratorInject = false
disableKinds = ["RSS"]
enableRobotsTXT = true
googleAnalytics = "#"
languageCode = "en-us"
layoutDir = "public/layouts"
publishDir = "public"
staticDir = "public/static"
title = "Jan Christian Bernabe"

[params]
  description = '<!--[-->Thought Leader | Creative Technophile | Growth Hacker<!--]--><br />
                <!--[-->Polymath<!--]-->'
  logo = "fa-bolt"
  copyright = "Jan Christian Bernabe, PhD"

[params.disqus]
  site = "#"

[params.google.analytics]
  trackerID = "#"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/janchristianbernabe"

[[params.social]]
  medium = "quora"
  icon = "quora"
  link = "https://www.quora.com/profile/Jan-Christian-Bernabe"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://www.twitter.com/spramp"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://www.github.com/spramp"

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Jan Christian Bernabe"
description = '<!--[-->Thought Leader | Creative Technophile | Growth Hacker<!--]--><br />
              <!--[-->Polymath<!--]-->'
