archetypeDir = "content/archetypes"
baseurl = "/"
config = "config.toml"
contentDir = "public/content"
dataDir = "public/data"
defaultContentLanguage = "en"
disable404 = false
disableHugoGeneratorInject = false
disableKinds = ["RSS"]
enableRobotsTXT = true
googleAnalytics = "#"
languageCode = "en-us"
layoutDir = "public/layouts"
publishDir = "public"
staticDir = "public/static"
title = "Jan Christian Bernabe"
uglyURLs = true

[params]
  description = '<!--[-->Thought Leader | Maker | Growth Hacker | Polymath<!--]--><p></p>
                <!--[--><i class="far fa-id-card fa-2x"></i><!--]--><br />
                <!--[--><p>Nerd</p><!--]-->'
  logo = "fas fa-bolt fa-2x"
  copyright = "Jan Christian Bernabe, Ph.D."

[params.disqus]
  site = "#"

[params.google.analytics]
  trackerID = "#"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/janchristianbernabe"

[[params.social]]
  medium = "amazon"
  icon = "amazon"
  link = "https://www.amazon.com/Jan-Christian-Bernabe/e/B06W541XK7/ref=dp_byline_cont_ebooks_2"

[[params.social]]
  medium = "quora"
  icon = "quora"
  link = "https://www.quora.com/profile/Jan-Christian-Bernabe"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://www.twitter.com/spramp"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://www.github.com/spramp"

[[params.social]]
    medium = "spotify"
    icon = "spotify"
    link = "https://open.spotify.com/user/spramp"

[languages]
[languages.en]
languageName = "English"
weight = 1
