archetypeDir = "content/archetypes"
baseurl = "/"
config = "config.toml"
contentDir = "public/content"
dataDir = "public/data"
defaultContentLanguage = "en"
disable404 = false
disableHugoGeneratorInject = false
disableKinds = ["RSS"]
enableRobotsTXT = true
googleAnalytics = "#"
languageCode = "en-us"
layoutDir = "public/layouts"
publishDir = "public"
staticDir = "public/static"
title = "Jan Christian Bernabe"

[params]
  description = '<!--[-->Thought Leader | Creative Technophile | Growth Hacker |<!--]--><br />
                <!--[-->Polymath<!--]-->'
  logo = "fas fa-bolt"
  copyright = "Jan Christian Bernabe, PhD"

[params.disqus]
  site = "#"

[params.google.analytics]
  trackerID = "#"

[[params.social]]
  medium = "linkedin"
  icon = "fas fa-linkedin"
  link = "https://www.linkedin.com/in/janchristianbernabe"

[[params.social]]
  medium = "amazon"
  icon = "fas fa-amazon"
  link = "https://www.amazon.com/Jan-Christian-Bernabe/e/B06W541XK7/ref=dp_byline_cont_ebooks_2"

[[params.social]]
  medium = "quora"
  icon = "fas fa-quora"
  link = "https://www.quora.com/profile/Jan-Christian-Bernabe"

[[params.social]]
  medium = "twitter"
  icon = "fas fa-twitter"
  link = "https://www.twitter.com/spramp"

[[params.social]]
  medium = "github"
  icon = "fas fa-github"
  link = "https://www.github.com/spramp"

[languages]
[languages.en]
languageName = "English"
weight = 1
